name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 使用这个极其稳定的 Action，它内置了所有安卓环境
      - name: Build Android APK
        uses: swantzter/create-android-project-action@v1
        with:
          # App 的名字
          app-name: "MyApkTest"
          # 包名，必须是三段式，且不能有中文
          package-id: "com.pan.apktest"
          # 网页代码目录，. 代表根目录
          web-dir: "."

      # 这一步是把生成的安卓工程编译成真正的 APK
      - name: Export APK
        uses: nwutils/default-build-action@v1
        with:
          output-path: "app-debug.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: "app-debug.apk"
