name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 这是一个更稳定的打包方案，直接调用现成的安卓环境
    - name: Build Android APK
      uses: Gear-Go/build-apk-action@v2
      with:
        app-name: "ApkTestApp"
        web-dir: "."

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: ./*.apk
